/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        /* Primitive color scale — mirrors CSS :root tokens */
        purple: {
          50:  '#faf5ff',
          100: '#f3e8ff',
          200: '#e9d5ff',
          300: '#d8b4fe',
          400: '#c084fc',
          500: '#a855f7',
          600: '#9333ea',
          700: '#7c3aed',
          800: '#6d28d9',
          900: '#5b21b6',
        },
        cyan: {
          50:  '#ecfeff',
          100: '#cffafe',
          200: '#a5f3fc',
          300: '#67e8f9',
          400: '#22d3ee',
          500: '#06b6d4',
          600: '#0891b2',
          700: '#0e7490',
          800: '#155e75',
          900: '#164e63',
        },
        slate: {
          50:  '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
        },

        /* Semantic brand colors */
        brand: {
          DEFAULT:   'var(--color-brand)',
          deep:      'var(--color-brand-deep)',
          light:     'var(--color-brand-light)',
          subtle:    'var(--color-brand-subtle)',
          accent:    'var(--color-accent)',
          'accent-deep':   'var(--color-accent-deep)',
          'accent-subtle': 'var(--color-accent-subtle)',
        },

        /* Semantic surface colors */
        surface: {
          page:     'var(--color-surface-page)',
          base:     'var(--color-surface-base)',
          elevated: 'var(--color-surface-elevated)',
          muted:    'var(--color-surface-muted)',
          overlay:  'var(--color-surface-overlay)',
          subtle:   'var(--color-surface-subtle)',
          glass:    'var(--color-surface-glass)',
        },

        /* Semantic text colors */
        text: {
          primary:   'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          tertiary:  'var(--color-text-tertiary)',
          inverse:   'var(--color-text-inverse)',
          brand:     'var(--color-text-brand)',
          link:      'var(--color-text-link)',
          placeholder: 'var(--color-text-placeholder)',
        },

        /* Semantic border colors */
        border: {
          default: 'var(--color-border-default)',
          subtle:  'var(--color-border-subtle)',
          strong:  'var(--color-border-strong)',
          brand:   'var(--color-border-brand)',
          focus:   'var(--color-border-focus)',
          error:   'var(--color-border-error)',
        },

        /* Semantic status colors */
        status: {
          success:       'var(--color-success)',
          'success-fg':  'var(--color-success-fg)',
          'success-bg':  'var(--color-success-bg)',
          warning:       'var(--color-warning)',
          'warning-fg':  'var(--color-warning-fg)',
          'warning-bg':  'var(--color-warning-bg)',
          error:         'var(--color-error)',
          'error-fg':    'var(--color-error-fg)',
          'error-bg':    'var(--color-error-bg)',
          info:          'var(--color-info)',
          'info-fg':     'var(--color-info-fg)',
          'info-bg':     'var(--color-info-bg)',
          neutral:       'var(--color-neutral)',
          'neutral-fg':  'var(--color-neutral-fg)',
          'neutral-bg':  'var(--color-neutral-bg)',
        },

        /* Severity colors (Bug-specific) */
        severity: {
          'fatal-fg':   'var(--color-severity-fatal-fg)',
          'fatal-bg':   'var(--color-severity-fatal-bg)',
          'major-fg':   'var(--color-severity-major-fg)',
          'major-bg':   'var(--color-severity-major-bg)',
          'normal-fg':  'var(--color-severity-normal-fg)',
          'normal-bg':  'var(--color-severity-normal-bg)',
          'minor-fg':   'var(--color-severity-minor-fg)',
          'minor-bg':   'var(--color-severity-minor-bg)',
          'suggest-fg': 'var(--color-severity-suggest-fg)',
          'suggest-bg': 'var(--color-severity-suggest-bg)',
        },
      },
      borderRadius: {
        'xs':   'var(--radius-xs)',
        'sm':   'var(--radius-sm)',
        'md':   'var(--radius-md)',
        'lg':   'var(--radius-lg)',
        'xl':   'var(--radius-xl)',
        '2xl':  'var(--radius-2xl)',
        '3xl':  'var(--radius-3xl)',
        'pill': 'var(--radius-pill)',
        /* Semantic aliases */
        'control': 'var(--radius-control)',
        'card':    'var(--radius-card)',
        'scene':   'var(--radius-scene)',
        'panel':   'var(--radius-panel)',
      },
      boxShadow: {
        'xs':    'var(--shadow-xs)',
        'sm':    'var(--shadow-sm)',
        'md':    'var(--shadow-md)',
        'lg':    'var(--shadow-lg)',
        'xl':    'var(--shadow-xl)',
        'brand': 'var(--shadow-brand)',
        'focus': 'var(--shadow-focus)',
        'error': 'var(--shadow-error)',
      },
      spacing: {
        '0.5':  'var(--space-0-5)',
        '1':    'var(--space-1)',
        '1.5':  'var(--space-1-5)',
        '2':    'var(--space-2)',
        '2.5':  'var(--space-2-5)',
        '3':    'var(--space-3)',
        '3.5':  'var(--space-3-5)',
        '4':    'var(--space-4)',
        '5':    'var(--space-5)',
        '6':    'var(--space-6)',
        '7':    'var(--space-7)',
        '8':    'var(--space-8)',
        '9':    'var(--space-9)',
        '10':   'var(--space-10)',
        '12':   'var(--space-12)',
        '14':   'var(--space-14)',
        '16':   'var(--space-16)',
        /* Semantic aliases */
        'section': 'var(--space-section)',
        'module':  'var(--space-module)',
        'control': 'var(--space-control)',
        'tight':   'var(--space-tight)',
        'cozy':    'var(--space-cozy)',
      },
      transitionDuration: {
        'fast':     'var(--duration-fast)',
        'normal':   'var(--duration-normal)',
        'slow':     'var(--duration-slow)',
        'entrance': 'var(--duration-entrance)',
      },
      transitionTimingFunction: {
        'default': 'var(--ease-default)',
        'in':      'var(--ease-in)',
        'out':     'var(--ease-out)',
        'spring':  'var(--ease-spring)',
      },
      fontFamily: {
        sans:    ['var(--font-sans)'],
        display: ['var(--font-display)'],
        mono:    ['var(--font-mono)'],
      },
      fontSize: {
        'micro':    ['var(--text-micro)',    { lineHeight: '1.4' }],
        'caption':  ['var(--text-caption)',  { lineHeight: '1.5' }],
        'body':     ['var(--text-body)',     { lineHeight: '1.6' }],
        'subhead':  ['var(--text-subhead)',  { lineHeight: '1.5' }],
        'title':    ['var(--text-title)',    { lineHeight: '1.35', fontWeight: '600' }],
        'heading':  ['var(--text-heading)',  { lineHeight: '1.25', fontWeight: '600' }],
        'display':  ['var(--text-display)',  { lineHeight: '1.2',  fontWeight: '700' }],
      },
      fontWeight: {
        'regular':  'var(--weight-regular)',
        'medium':   'var(--weight-medium)',
        'semibold': 'var(--weight-semibold)',
        'bold':     'var(--weight-bold)',
      },
      letterSpacing: {
        'tight':  'var(--tracking-tight)',
        'normal': 'var(--tracking-normal)',
        'wide':   'var(--tracking-wide)',
        'wider':  'var(--tracking-wider)',
        'widest': 'var(--tracking-widest)',
      },
      zIndex: {
        'base':     'var(--z-base)',
        'dropdown': 'var(--z-dropdown)',
        'sticky':   'var(--z-sticky)',
        'overlay':  'var(--z-overlay)',
        'modal':    'var(--z-modal)',
        'toast':    'var(--z-toast)',
      },
    },
  },
  plugins: [],
  corePlugins: {
    preflight: false,
  },
}
