/**
 * 关系阶段截图生成器的英文场景目录。
 *
 * 每个阶段固定保留三个阶段准确案例与两个建设性案例。锚点提供生成长对话时不可丢失的
 * 阶段证据，收尾则刻意停在当前阶段，避免截图数据把关系误标为下一阶段。
 */

/**
 * 统一构造不可变更的场景外形，避免 80 个案例在字段命名上产生漂移。
 */
function scenario(track, slug, title, premise, topic, anchors, closing) {
  return { track, slug, title, premise, topic, anchors, closing };
}

/** 生成器按此字面量的插入顺序遍历，顺序必须与 dataset.cjs 的冻结枚举一致。 */
const STAGE_SCENARIOS = {
  UNCLEAR: [
    scenario("stage_accurate", "casual-check-in", "Casual Check In", "Two people exchange an occasional friendly message without naming the connection.", "intermittent small talk", [
      { speaker: "self", text: "I saw the rain today and remembered your story about getting caught in it." },
      { speaker: "other", text: "That made me smile. How have you been lately?" },
      { speaker: "self", text: "Pretty busy, but good. It is nice to hear from you." },
      { speaker: "other", text: "Same here. We seem to check in whenever life slows down." },
      { speaker: "self", text: "We have no expectations or label yet, and I am happy to leave this open." },
    ], [{ speaker: "other", text: "Let us keep in touch when it feels natural." }, { speaker: "self", text: "Sounds good, take care." }]),
    scenario("stage_accurate", "shared-interest-chat", "Shared Interest Chat", "They discover a common interest but have not defined what the connection is.", "shared interest", [
      { speaker: "self", text: "Your post about old films made me look up that director." },
      { speaker: "other", text: "I did not know you liked those films too." },
      { speaker: "self", text: "I am still learning, but I enjoyed the one you mentioned." },
      { speaker: "other", text: "Maybe we can trade recommendations sometime." },
      { speaker: "self", text: "We only share this interest so far, and I am happy to keep it simple." },
    ], [{ speaker: "other", text: "I feel the same, and I will still put together that short film list." }, { speaker: "self", text: "Great, I will do the same." }]),
    scenario("stage_accurate", "warm-return", "Warm Return", "After a long silence, they reconnect with warmth while leaving their status open.", "warm reconnection", [
      { speaker: "self", text: "It has been a long time. I hope your new job is going well." },
      { speaker: "other", text: "Thank you for asking. It has been an adjustment, but a good one." },
      { speaker: "self", text: "I am glad. I always appreciated how thoughtful you are." },
      { speaker: "other", text: "That is kind of you. I am happy we crossed paths again." },
      { speaker: "self", text: "This is only a warm catch up for now, with no expectations attached." },
    ], [{ speaker: "other", text: "I agree. This was a welcome surprise." }, { speaker: "self", text: "Talk again soon if you feel like it." }]),
    scenario("constructive", "continue-the-conversation", "Continue the Conversation", "They suggest talking again, while being honest that neither knows the intent yet.", "open-ended continuation", [
      { speaker: "self", text: "I have enjoyed this conversation more than I expected." },
      { speaker: "other", text: "Me too. I am not sure what it means yet, and that is okay." },
      { speaker: "self", text: "I appreciate you saying that clearly." },
      { speaker: "other", text: "Would you want to keep talking and see what we learn?" },
      { speaker: "self", text: "Let us keep talking without deciding what this is yet." },
    ], [{ speaker: "other", text: "That feels comfortable to me." }, { speaker: "self", text: "Then we can simply keep talking." }]),
    scenario("constructive", "background-to-share", "Background To Share", "One person prepares to explain more context, but neither draws a conclusion about the relationship.", "sharing context", [
      { speaker: "self", text: "I am glad we can talk, but I still do not know what kind of connection this is." },
      { speaker: "other", text: "I feel the same; neither of us has named an intention for staying in touch." },
      { speaker: "self", text: "I have background about why I went quiet, but sharing it will not answer what this means." },
      { speaker: "other", text: "That is okay. I would rather hear it without turning it into a relationship decision." },
      { speaker: "self", text: "I will share the background later; there is no conclusion for us to make now." },
    ], [{ speaker: "other", text: "Take your time, there is no rush." }, { speaker: "self", text: "I appreciate the patience." }]),
  ],
  NEW_CONNECTION: [
    scenario("stage_accurate", "bookstore-introduction", "Bookstore Introduction", "They meet at a bookstore and exchange a first friendly message afterward.", "bookstore meeting", [
      { speaker: "self", text: "Hi, I am the person who asked about the poetry shelf today." },
      { speaker: "other", text: "Hi! I remember. Did you end up choosing a book?" },
      { speaker: "self", text: "I picked the collection you suggested." },
      { speaker: "other", text: "I hope it works for you. I would love to hear what you think." },
      { speaker: "self", text: "We only just met today, so I am glad to start with a book recommendation." },
    ], [{ speaker: "other", text: "Nice meeting you today." }, { speaker: "self", text: "Nice meeting you too." }]),
    scenario("stage_accurate", "introduced-by-sam", "Introduced By Sam", "A mutual acquaintance connects them, and they begin with a low-pressure hello.", "mutual introduction", [
      { speaker: "self", text: "Sam said we both enjoy hiking, so I wanted to say hello." },
      { speaker: "other", text: "Sam mentioned you too. It is nice to meet you." },
      { speaker: "self", text: "What trails have you liked recently?" },
      { speaker: "other", text: "Mostly easy local ones while I get back into it." },
      { speaker: "self", text: "Since Sam introduced us, it is nice to begin with a simple hello." },
    ], [{ speaker: "other", text: "Thanks for reaching out." }, { speaker: "self", text: "Glad Sam made the introduction." }]),
    scenario("stage_accurate", "volunteer-follow-up", "Volunteer Follow Up", "They speak for the first time after working at the same volunteer event.", "volunteer event", [
      { speaker: "self", text: "It was good working the food table with you yesterday." },
      { speaker: "other", text: "You made the busy hour much calmer." },
      { speaker: "self", text: "I was glad we figured out the system together." },
      { speaker: "other", text: "Are you planning to volunteer next month too?" },
      { speaker: "self", text: "Yes, I am planning to sign up, and I would be glad to say hello again." },
    ], [{ speaker: "other", text: "I will look for the sign-up date." }, { speaker: "self", text: "Let me know if you find it first." }]),
    scenario("constructive", "exchange-interests", "Exchange Interests", "They exchange interests and agree to keep learning about each other at an easy pace.", "interest exchange", [
      { speaker: "self", text: "I am curious what you enjoy outside of work." },
      { speaker: "other", text: "I cook, read mysteries, and try to get outside on weekends." },
      { speaker: "self", text: "That is a fun mix. I play music and make simple meals." },
      { speaker: "other", text: "I would enjoy hearing more about the music sometime." },
      { speaker: "self", text: "We are still just getting acquainted through the things we enjoy." },
    ], [{ speaker: "other", text: "We have plenty left to discover." }, { speaker: "self", text: "I am looking forward to that." }]),
    scenario("constructive", "group-game-night", "Group Game Night", "They confirm a relaxed group activity as a way to continue getting acquainted.", "group activity", [
      { speaker: "self", text: "We only met recently, and the group game night seems like a nice way to get acquainted." },
      { speaker: "other", text: "I agree. A group activity feels low pressure while we get to know each other." },
      { speaker: "self", text: "A few friends will be there, and the games are cooperative, so no one needs experience." },
      { speaker: "other", text: "That sounds comfortable for getting to know each other in a group." },
      { speaker: "self", text: "I am looking forward to meeting more people in the group, including you." },
    ], [{ speaker: "other", text: "Thanks, I am glad to be included." }, { speaker: "self", text: "It will be a relaxed first group activity together." }]),
  ],
  FRIENDS: [
    scenario("stage_accurate", "friends-weekend-plan", "Friends Weekend Plan", "Established friends organize time with their wider friend group.", "friend group plans", [
      { speaker: "self", text: "Should we invite everyone for a picnic next Saturday?" },
      { speaker: "other", text: "Yes, the group has not been together in a while." },
      { speaker: "self", text: "I can bring drinks if you handle the shared list." },
      { speaker: "other", text: "Done. You are always good at getting us organized." },
      { speaker: "self", text: "That is what I value about our friendship: we show up for the group." },
    ], [{ speaker: "other", text: "I am glad we make a good team." }, { speaker: "self", text: "Me too, see you Saturday." }]),
    scenario("stage_accurate", "painting-class-pals", "Painting Class Pals", "Friends support each other through a hobby they share.", "shared hobby", [
      { speaker: "self", text: "Are you bringing your sketchbook to class tonight?" },
      { speaker: "other", text: "Yes, but I am nervous about showing anything." },
      { speaker: "self", text: "Your color choices are always interesting. I hope you share one." },
      { speaker: "other", text: "Thanks, that helps coming from a friend." },
      { speaker: "self", text: "As your friend, I am happy to encourage you without any pressure." },
    ], [{ speaker: "other", text: "That would make it easier." }, { speaker: "self", text: "I saved us two seats." }]),
    scenario("stage_accurate", "work-stress-support", "Work Stress Support", "One friend listens while the other processes work stress.", "work support", [
      { speaker: "self", text: "Today at work was rough, and I need to vent for a minute." },
      { speaker: "other", text: "I have space to listen. Do you want advice or just company?" },
      { speaker: "self", text: "Mostly company. I do not want to carry it alone." },
      { speaker: "other", text: "I am here. You handled a hard day." },
      { speaker: "self", text: "Thank you for being the kind of friend I can lean on after work." },
    ], [{ speaker: "other", text: "You do the same for me." }, { speaker: "self", text: "That means a lot." }]),
    scenario("constructive", "clear-up-misunderstanding", "Clear Up A Misunderstanding", "Friends repair a small misunderstanding with direct and respectful communication.", "friendship repair", [
      { speaker: "self", text: "I felt left out when the plan changed and I did not hear about it." },
      { speaker: "other", text: "I am sorry. I assumed someone else had told you, and that was careless." },
      { speaker: "self", text: "Thank you for hearing me. I did not want resentment to grow." },
      { speaker: "other", text: "I value our friendship and will check directly next time." },
      { speaker: "self", text: "Repairing this matters to me because I value our friendship." },
    ], [{ speaker: "other", text: "I am glad we talked it through." }, { speaker: "self", text: "Me too, we are okay." }]),
    scenario("constructive", "friendship-appreciation", "Friendship Appreciation", "They explicitly affirm that their friendship matters to both of them.", "valuing friendship", [
      { speaker: "self", text: "I have been thinking about how much I value our friendship." },
      { speaker: "other", text: "I feel the same. You make ordinary weeks better." },
      { speaker: "self", text: "I trust you, and I do not take that for granted." },
      { speaker: "other", text: "Thank you. I am grateful we found this friendship." },
      { speaker: "self", text: "I want to protect and celebrate this friendship, exactly as it is." },
    ], [{ speaker: "other", text: "I am lucky to call you my friend." }, { speaker: "self", text: "Likewise." }]),
  ],
  TALKING: [
    scenario("stage_accurate", "daily-check-ins", "Daily Check Ins", "They are getting to know each other through steady, ordinary conversations.", "daily conversation", [
      { speaker: "self", text: "How did your presentation go today?" },
      { speaker: "other", text: "Better than I expected. I remembered your advice to slow down." },
      { speaker: "self", text: "I am glad it helped. What are you doing to unwind now?" },
      { speaker: "other", text: "Making soup and catching up on a podcast." },
      { speaker: "self", text: "These everyday check ins are helping us get to know each other steadily." },
    ], [{ speaker: "other", text: "Thanks for asking about it." }, { speaker: "self", text: "I like hearing about your day." }]),
    scenario("stage_accurate", "values-conversation", "Values Conversation", "Their ongoing conversation turns to values and how they make decisions.", "values discussion", [
      { speaker: "self", text: "What helps you decide when work and family need you at once?" },
      { speaker: "other", text: "I try to be honest about capacity and protect time for both." },
      { speaker: "self", text: "I respect that. Balance matters to me too." },
      { speaker: "other", text: "It takes practice. What value guides you most?" },
      { speaker: "self", text: "Steadiness guides me most, and talking about values helps me understand you beyond casual conversation." },
    ], [{ speaker: "other", text: "That is useful to know about you." }, { speaker: "self", text: "I am enjoying learning this kind of thing." }]),
    scenario("stage_accurate", "regular-voice-notes", "Regular Voice Notes", "They have developed a reliable rhythm of messages and voice notes.", "regular voice notes", [
      { speaker: "self", text: "Your voice note made my commute much better." },
      { speaker: "other", text: "I am glad. I like our little updates during the week." },
      { speaker: "self", text: "They help me feel connected to what is going on with you." },
      { speaker: "other", text: "Same. Texting is easy, but hearing your thoughts adds more." },
      { speaker: "self", text: "Our regular voice notes and calls are a good way to keep learning about each other." },
    ], [{ speaker: "other", text: "Yes, that rhythm works for me." }, { speaker: "self", text: "Great, let us try it this week." }]),
    scenario("constructive", "contact-rhythm", "Contact Rhythm", "They agree on a sustainable communication rhythm without assigning a label.", "communication rhythm", [
      { speaker: "self", text: "I like talking often, but I do not want either of us to feel on call." },
      { speaker: "other", text: "I agree. Weekday messages and one weekend call feel realistic." },
      { speaker: "self", text: "That works for me. We can say when a busy week changes it." },
      { speaker: "other", text: "Yes, a quick heads up would help me avoid guessing." },
      { speaker: "self", text: "We are building a steady talking rhythm without putting a label on it." },
    ], [{ speaker: "other", text: "It makes getting to know each other feel easy." }, { speaker: "self", text: "That is exactly what I want." }]),
    scenario("constructive", "group-outing-follow-up", "Group Outing Follow Up", "They continue learning about each other through a group event and follow-up chat.", "group activity follow-up", [
      { speaker: "self", text: "I have liked our one-on-one chats this week, and it was nice to see you in the group today." },
      { speaker: "other", text: "Me too. We have been talking regularly, and I like learning about you in different settings." },
      { speaker: "self", text: "I am not trying to label this yet; I just enjoy our ongoing conversations." },
      { speaker: "other", text: "I feel the same. We are still getting to know each other through steady chats." },
      { speaker: "self", text: "Group time is helping us get to know each other naturally, without making it more than that." },
    ], [{ speaker: "other", text: "I am glad we can keep learning about each other in the group." }, { speaker: "self", text: "I will see you at the next group plan." }]),
  ],
  FLIRTING: [
    scenario("stage_accurate", "mutual-compliments", "Mutual Compliments", "They exchange warm compliments that make the attraction more visible.", "mutual compliments", [
      { speaker: "self", text: "You have a way of making every room feel more relaxed." },
      { speaker: "other", text: "That is a lovely thing to hear from you." },
      { speaker: "self", text: "I mean it. You also have a great laugh." },
      { speaker: "other", text: "Careful, I might start smiling every time you message." },
      { speaker: "self", text: "That is me flirting with you, and I like that it makes you smile." },
    ], [{ speaker: "other", text: "You are charming when you are sincere." }, { speaker: "self", text: "Then I will keep being sincere." }]),
    scenario("stage_accurate", "playful-teasing", "Playful Teasing", "They use gentle teasing that both people clearly enjoy.", "playful teasing", [
      { speaker: "self", text: "You call that a playlist? It has three versions of the same song." },
      { speaker: "other", text: "It is called commitment to a mood." },
      { speaker: "self", text: "I admire your dedication, even if it is dramatic." },
      { speaker: "other", text: "You secretly like the drama." },
      { speaker: "self", text: "I am teasing because I enjoy the playful spark between us." },
    ], [{ speaker: "other", text: "That answer was smooth." }, { speaker: "self", text: "I have my moments." }]),
    scenario("stage_accurate", "name-the-chemistry", "Name The Chemistry", "They acknowledge a mutual spark without making plans or defining anything further.", "mutual chemistry", [
      { speaker: "self", text: "I feel a little extra energy when we talk." },
      { speaker: "other", text: "I have noticed that too." },
      { speaker: "self", text: "I did not want to pretend it was not there." },
      { speaker: "other", text: "Thank you for saying it. The chemistry feels real to me." },
      { speaker: "self", text: "I am glad we can admit there is chemistry without making plans around it." },
    ], [{ speaker: "other", text: "We can enjoy that feeling without rushing it." }, { speaker: "self", text: "I like that approach." }]),
    scenario("constructive", "sweet-nickname-check", "Sweet Nickname Check", "They ask consent before using a more affectionate nickname.", "consensual nicknames", [
      { speaker: "self", text: "I have been tempted to call you sunshine, but I wanted to ask first." },
      { speaker: "other", text: "I like that you asked. Sunshine feels sweet to me." },
      { speaker: "self", text: "Good. Please tell me if it ever stops feeling right." },
      { speaker: "other", text: "I will. What nickname would feel good for you?" },
      { speaker: "self", text: "I like \"bright eyes,\" but please ask each time at first." },
    ], [{ speaker: "other", text: "Then I will ask before calling you bright eyes." }, { speaker: "self", text: "That made me grin." }]),
    scenario("constructive", "say-the-flirting", "Say The Flirting", "They directly acknowledge that they enjoy flirting with each other.", "naming flirtation", [
      { speaker: "self", text: "I want to check something. Are you flirting with me?" },
      { speaker: "other", text: "Yes, gently and on purpose. I hope it feels welcome." },
      { speaker: "self", text: "It does. I have been flirting back." },
      { speaker: "other", text: "That makes me happy to hear." },
      { speaker: "self", text: "I enjoy flirting with you, and I want it to keep feeling welcome." },
    ], [{ speaker: "other", text: "We can keep checking in as we go." }, { speaker: "self", text: "Absolutely." }]),
  ],
  SITUATIONSHIP: [
    scenario("stage_accurate", "unlabeled-routine", "Unlabeled Routine", "They share a couple-like daily routine but have not agreed on a label.", "unlabeled daily closeness", [
      { speaker: "self", text: "I noticed we talk before bed almost every night now." },
      { speaker: "other", text: "It has become part of my day too." },
      { speaker: "self", text: "We do a lot that feels close, even without a name for it." },
      { speaker: "other", text: "I know. I enjoy it, but I have not defined it in my head." },
      { speaker: "self", text: "We act close every day, but we still have not defined what we are." },
    ], [{ speaker: "other", text: "For now, I am glad we can be honest about the uncertainty." }, { speaker: "self", text: "Me too." }]),
    scenario("stage_accurate", "close-weekend-undefined", "Close Weekend Undefined", "They spent an intimate weekend together and recognize that the status remains undefined.", "undefined intimacy", [
      { speaker: "self", text: "This weekend felt really close to me." },
      { speaker: "other", text: "It did to me too, and I am glad we had that time." },
      { speaker: "self", text: "I am noticing I do not know how to describe us afterward." },
      { speaker: "other", text: "I do not have a clear answer yet either." },
      { speaker: "self", text: "We shared a close weekend, but our connection is still undefined." },
    ], [{ speaker: "other", text: "Thank you for not assuming." }, { speaker: "self", text: "We can keep being thoughtful about it." }]),
    scenario("stage_accurate", "unclear-expectations", "Unclear Expectations", "They surface mismatched expectations without resolving the relationship status.", "unclear expectations", [
      { speaker: "self", text: "Sometimes I expect to hear from you, then I remember we never discussed that." },
      { speaker: "other", text: "I did not realize you were carrying that expectation." },
      { speaker: "self", text: "I am not blaming you. I want us to understand what each person expects." },
      { speaker: "other", text: "That is fair. I need time to think about what I can offer." },
      { speaker: "self", text: "Until we define this, neither of us should assume the other person's expectations." },
    ], [{ speaker: "other", text: "Let us revisit it after I reflect." }, { speaker: "self", text: "Okay, I can give it space." }]),
    scenario("constructive", "ask-for-clarity", "Ask For Clarity", "One person calmly says they need to think more clearly about what this connection is.", "requesting clarity", [
      { speaker: "self", text: "I care about what we have, and I need to think more clearly about what it is." },
      { speaker: "other", text: "I understand. I have been avoiding that question because I was unsure." },
      { speaker: "self", text: "I am not asking for an answer tonight." },
      { speaker: "other", text: "That helps. I want to reflect honestly, not give a rushed answer." },
      { speaker: "self", text: "I need clarity about this undefined connection, but I am not asking for a label tonight." },
    ], [{ speaker: "other", text: "I hear you, and I will take time to think without forcing an answer tonight." }, { speaker: "self", text: "Thank you for taking it seriously." }]),
    scenario("constructive", "temporary-boundaries", "Temporary Boundaries", "They set temporary boundaries while postponing a fuller definition of the connection.", "temporary boundaries", [
      { speaker: "self", text: "Until we talk more, I need our plans to be a little more predictable." },
      { speaker: "other", text: "That is reasonable. What would help?" },
      { speaker: "self", text: "A clear yes or no by the day before, and no late night drop-ins." },
      { speaker: "other", text: "I can respect that. It gives us both room to think." },
      { speaker: "self", text: "Let us use these boundaries for now while we figure out what this is." },
    ], [{ speaker: "other", text: "I will follow those boundaries." }, { speaker: "self", text: "We can revisit them when we talk again." }]),
  ],
  DATE_PLANNING: [
    scenario("stage_accurate", "first-coffee-plan", "First Coffee Plan", "They arrange a first coffee date that has not happened yet.", "first coffee date", [
      { speaker: "self", text: "Would you like to get coffee together this Saturday?" },
      { speaker: "other", text: "Yes, I would like that. A morning coffee sounds comfortable." },
      { speaker: "self", text: "How does ten at the cafe near the park sound?" },
      { speaker: "other", text: "Ten works for me. Thank you for suggesting something simple." },
      { speaker: "self", text: "Saturday morning is in my calendar, and I am looking forward to meeting for coffee." },
    ], [{ speaker: "other", text: "Me too. See you Saturday." }, { speaker: "self", text: "See you then." }]),
    scenario("stage_accurate", "first-dinner-plan", "First Dinner Plan", "They choose a low-pressure dinner for a first date, still in the planning stage.", "first dinner date", [
      { speaker: "self", text: "Would dinner next week feel good for a first date?" },
      { speaker: "other", text: "Yes. I would prefer somewhere quiet enough to talk." },
      { speaker: "self", text: "I know a small place with simple food and calm tables." },
      { speaker: "other", text: "That sounds good. Thursday evening is open for me." },
      { speaker: "self", text: "Thursday evening is in my calendar for our first dinner together." },
    ], [{ speaker: "other", text: "Thank you, I am looking forward to it." }, { speaker: "self", text: "I am too." }]),
    scenario("stage_accurate", "museum-first-date", "Museum First Date", "They plan a first date at a museum and keep expectations clear.", "museum first date", [
      { speaker: "self", text: "Would you be interested in visiting the museum together next weekend?" },
      { speaker: "other", text: "Yes, a museum date sounds fun and easy to talk through." },
      { speaker: "self", text: "We could meet at the entrance at noon." },
      { speaker: "other", text: "Noon works. I would like to take it at a relaxed pace." },
      { speaker: "self", text: "I will meet you at noon next weekend, and we can take the museum at our own pace." },
    ], [{ speaker: "other", text: "That sounds comfortable." }, { speaker: "self", text: "Then the museum it is." }]),
    scenario("constructive", "respectful-reschedule", "Respectful Reschedule", "They reschedule a planned first date with care and without guilt.", "date rescheduling", [
      { speaker: "self", text: "I need to reschedule our first date tomorrow because a family matter came up." },
      { speaker: "other", text: "Thank you for telling me early. I hope everything is okay." },
      { speaker: "self", text: "I would still like to meet when things settle. Would next Wednesday work for you?" },
      { speaker: "other", text: "Next Wednesday works, and I appreciate keeping the plan low pressure." },
      { speaker: "self", text: "Then let us move our first date to Wednesday and check in the day before." },
    ], [{ speaker: "other", text: "Take care of what you need to handle." }, { speaker: "self", text: "Thank you. I will confirm on Tuesday." }]),
    scenario("constructive", "comfort-and-access", "Comfort And Access", "They confirm comfort and accessibility needs before their first date occurs.", "date accessibility", [
      { speaker: "self", text: "Before our first date, is there anything that would make the plan more comfortable for you?" },
      { speaker: "other", text: "Thank you for asking. For a first date, I do better with a quiet place and step-free entry." },
      { speaker: "self", text: "I can choose a cafe with both. Would a shorter meeting help?" },
      { speaker: "other", text: "Yes, an hour or so would make the first meeting feel good." },
      { speaker: "self", text: "I want our plan to fit your access and comfort needs." },
    ], [{ speaker: "other", text: "That makes me feel considered before we meet." }, { speaker: "self", text: "Your comfort matters in planning the date." }]),
  ],
  DATING: [
    scenario("stage_accurate", "after-first-date", "After The First Date", "They reflect warmly after their first date and remain in the early dating stage.", "first date follow-up", [
      { speaker: "self", text: "I had a really good time getting coffee with you today." },
      { speaker: "other", text: "I did too. I felt comfortable talking with you." },
      { speaker: "self", text: "I especially liked hearing about your family traditions." },
      { speaker: "other", text: "I liked how curious you were without making it feel like an interview." },
      { speaker: "self", text: "I enjoyed our first date and would like another date while we keep getting to know each other." },
    ], [{ speaker: "other", text: "Yes, I would like another date." }, { speaker: "self", text: "That makes me happy." }]),
    scenario("stage_accurate", "after-third-date", "After The Third Date", "After several dates, they share appreciation while still learning the fit.", "third date reflection", [
      { speaker: "self", text: "Three dates in, I am enjoying how easy our conversations feel." },
      { speaker: "other", text: "I feel that too. I also like that we can disagree without it getting tense." },
      { speaker: "self", text: "I am still learning what works for both of us." },
      { speaker: "other", text: "Same. I like taking the time to notice that." },
      { speaker: "self", text: "After three dates, I would like to keep dating and learning our fit." },
    ], [{ speaker: "other", text: "I would like that too." }, { speaker: "self", text: "Good, let us keep it intentional." }]),
    scenario("stage_accurate", "values-on-a-date", "Values On A Date", "During ongoing dating, they compare practical values and compatibility.", "dating values", [
      { speaker: "self", text: "I have enjoyed our dates, and I am curious how you think about money and time." },
      { speaker: "other", text: "I plan carefully, but I also make room for small adventures." },
      { speaker: "self", text: "That is close to how I approach it. I value steadiness and generosity." },
      { speaker: "other", text: "It is good to talk about these things while we are dating." },
      { speaker: "self", text: "While we are dating, I want to test compatibility through real values conversations." },
    ], [{ speaker: "other", text: "I appreciate the openness." }, { speaker: "self", text: "Me too." }]),
    scenario("constructive", "scheduling-repair", "Scheduling Repair", "They repair a small scheduling friction while continuing to date.", "dating schedule repair", [
      { speaker: "self", text: "I felt disappointed when our date last Saturday changed at the last minute." },
      { speaker: "other", text: "I understand. I should have updated you sooner instead of leaving you waiting." },
      { speaker: "self", text: "I want to keep dating you, but early notice helps me feel respected when plans change." },
      { speaker: "other", text: "I want to keep dating too, and I will contact you as soon as I know next time." },
      { speaker: "self", text: "We are still dating, and I want our next date to be planned more reliably." },
    ], [{ speaker: "other", text: "How about Sunday afternoon?" }, { speaker: "self", text: "Sunday sounds good." }]),
    scenario("constructive", "pace-and-boundaries", "Pace And Boundaries", "They discuss dating pace and physical boundaries with consent and clarity.", "dating boundaries", [
      { speaker: "self", text: "I am enjoying dating you, and I want to talk about pace and physical boundaries." },
      { speaker: "other", text: "I am glad you brought it up. I prefer to go slowly and check in often." },
      { speaker: "self", text: "That works for me. I will ask rather than assume." },
      { speaker: "other", text: "Thank you. I will be clear if I need to pause or change course." },
      { speaker: "self", text: "I want to keep dating at a pace where both of our physical boundaries are respected." },
    ], [{ speaker: "other", text: "I feel the same." }, { speaker: "self", text: "Good, we can keep communicating." }]),
  ],
  DEFINING_RELATIONSHIP: [
    scenario("stage_accurate", "what-are-we", "What Are We", "They initiate a direct conversation about what their connection means, without deciding it yet.", "relationship definition", [
      { speaker: "self", text: "I have been wondering, are we dating, and what are we to each other?" },
      { speaker: "other", text: "I have been wondering too, but I am not ready to decide on a relationship label." },
      { speaker: "self", text: "Could we talk about what we are and deliberately postpone the decision?" },
      { speaker: "other", text: "Yes. I want to discuss it honestly, then take time before we define the relationship." },
      { speaker: "self", text: "I am asking what we are, but I am not asking us to decide the relationship tonight." },
    ], [{ speaker: "other", text: "Let us make space to discuss it without deciding tonight." }, { speaker: "self", text: "Thank you for keeping the question open with me." }]),
    scenario("stage_accurate", "labels-discussion", "Labels Discussion", "They discuss possible labels and what each would mean, leaving the decision open.", "label discussion", [
      { speaker: "self", text: "When you hear a relationship label, what does it mean to you?" },
      { speaker: "other", text: "For me, it suggests intention, care, and shared expectations." },
      { speaker: "self", text: "I hear that. I want to understand it before choosing any words." },
      { speaker: "other", text: "Same. A label should describe reality, not create pressure." },
      { speaker: "self", text: "We are discussing what labels mean to us, not choosing one yet." },
    ], [{ speaker: "other", text: "We do not need to settle it this minute." }, { speaker: "self", text: "Agreed." }]),
    scenario("stage_accurate", "exclusivity-possibility", "Exclusivity Possibility", "They consider whether exclusivity could fit but do not make that agreement yet.", "considering exclusivity", [
      { speaker: "self", text: "I have been thinking about whether exclusivity is something we should discuss." },
      { speaker: "other", text: "I am open to talking about it, though I need time to understand my feelings." },
      { speaker: "self", text: "That makes sense. I do not want an answer before you are ready." },
      { speaker: "other", text: "I appreciate that. It matters enough to think through carefully." },
      { speaker: "self", text: "Exclusivity is only a possibility we are considering, not an agreement today." },
    ], [{ speaker: "other", text: "Yes, and revisit it soon." }, { speaker: "self", text: "That works for me." }]),
    scenario("constructive", "align-expectations-later", "Align Expectations Later", "They identify expectations and consciously postpone a final relationship decision.", "expectations alignment", [
      { speaker: "self", text: "I want us to compare expectations before we decide what to call this." },
      { speaker: "other", text: "I want regular communication and room for my existing commitments." },
      { speaker: "self", text: "I want reliability and honesty when plans or feelings change." },
      { speaker: "other", text: "Those sound compatible, but I would like a few days to reflect." },
      { speaker: "self", text: "Our expectations are clearer, but we are deliberately delaying any relationship decision." },
    ], [{ speaker: "other", text: "Thank you for not forcing a decision." }, { speaker: "self", text: "I want it to be mutual and considered." }]),
    scenario("constructive", "questions-before-label", "Questions Before Label", "They make a practical question list before confirming any relationship label.", "definition questions", [
      { speaker: "self", text: "Could we write down the questions we each need answered before deciding?" },
      { speaker: "other", text: "Yes. I want to ask about time, communication, and long-term hopes." },
      { speaker: "self", text: "I also want to ask about boundaries and how we handle conflict." },
      { speaker: "other", text: "That list will help us be more thoughtful." },
      { speaker: "self", text: "We will answer these questions before confirming any label or agreement." },
    ], [{ speaker: "other", text: "I will bring my questions too." }, { speaker: "self", text: "Good, no decision until we are ready." }]),
  ],
  EXCLUSIVE: [
    scenario("stage_accurate", "choose-only-us", "Choose Only Us", "They clearly agree to focus romantically only on each other, without adopting partner labels.", "exclusive agreement", [
      { speaker: "self", text: "I want to focus on getting to know only you romantically." },
      { speaker: "other", text: "I want that too. I am not pursuing anyone else." },
      { speaker: "self", text: "Then can we agree to be exclusive while we keep learning together?" },
      { speaker: "other", text: "Yes, I am comfortable making that agreement." },
      { speaker: "self", text: "We have agreed to date only each other, without changing our labels." },
    ], [{ speaker: "other", text: "We are choosing each other right now." }, { speaker: "self", text: "Exactly." }]),
    scenario("stage_accurate", "pause-dating-apps", "Pause Dating Apps", "They agree to stop using dating apps as part of their exclusive agreement.", "dating apps pause", [
      { speaker: "self", text: "Since we agreed to be exclusive, I plan to pause my dating apps." },
      { speaker: "other", text: "I have already been thinking the same thing." },
      { speaker: "self", text: "I do not need proof, but I want our agreement to be mutual." },
      { speaker: "other", text: "It is mutual. I will pause mine today too." },
      { speaker: "self", text: "Our exclusive agreement means we are both pausing dating apps and outside romantic pursuit." },
    ], [{ speaker: "other", text: "I am glad we are aligned." }, { speaker: "self", text: "Me too." }]),
    scenario("stage_accurate", "exclusive-boundaries", "Exclusive Boundaries", "They clarify what exclusivity means in practice for each of them.", "exclusive boundaries", [
      { speaker: "self", text: "When we say exclusive, I want to be clear about what that includes." },
      { speaker: "other", text: "For me, it means no romantic or sexual connections with other people." },
      { speaker: "self", text: "That is my understanding too, and I would tell you if anything felt unclear." },
      { speaker: "other", text: "I would do the same instead of making assumptions." },
      { speaker: "self", text: "We are exclusive, and our boundary is no romantic or sexual connection with anyone else." },
    ], [{ speaker: "other", text: "We can revisit boundaries as needed." }, { speaker: "self", text: "Yes, openly." }]),
    scenario("constructive", "exclusive-contact-rhythm", "Exclusive Contact Rhythm", "They negotiate contact frequency while keeping their new exclusive agreement realistic.", "exclusive communication rhythm", [
      { speaker: "self", text: "Now that we have agreed to be exclusive and see only each other, I do not expect constant contact." },
      { speaker: "other", text: "I agree. I am not dating or pursuing anyone else, and a few real conversations each week feel right." },
      { speaker: "self", text: "Our exclusive agreement feels caring when we set a rhythm that does not crowd either of us." },
      { speaker: "other", text: "Yes, and if work changes the rhythm, I will tell the person I am exclusive with rather than disappear." },
      { speaker: "self", text: "We are exclusive, and this contact rhythm keeps the agreement caring and realistic." },
    ], [{ speaker: "other", text: "It makes exclusivity feel sustainable." }, { speaker: "self", text: "That is important to me." }]),
    scenario("constructive", "reassure-exclusive-concern", "Reassure Exclusive Concern", "They address a concern and reaffirm their exclusive agreement without changing labels.", "exclusive reassurance", [
      { speaker: "self", text: "I felt unsettled when I saw an old match message you had not answered." },
      { speaker: "other", text: "I understand why. I did not respond, and I should have cleared it sooner." },
      { speaker: "self", text: "Thank you for explaining. I need reassurance that our agreement still matters." },
      { speaker: "other", text: "It does. I am choosing exclusivity with you and will remove old conversations." },
      { speaker: "self", text: "I still want to honor our exclusive agreement, and direct reassurance helps me do that." },
    ], [{ speaker: "other", text: "Please bring concerns to me early." }, { speaker: "self", text: "I will." }]),
  ],
  RELATIONSHIP: [
    scenario("stage_accurate", "steady-partner-routine", "Steady Partner Routine", "Committed partners share ordinary daily support in a stable relationship.", "partner daily life", [
      { speaker: "self", text: "As your partner, do you want me to pick up groceries for our home after work?" },
      { speaker: "other", text: "That would help a lot, partner. Our relationship makes shared errands feel caring, not assumed." },
      { speaker: "self", text: "Of course. In our relationship, I want us to share the ordinary work of daily life." },
      { speaker: "other", text: "Thank you. I love how we take care of the small things as established partners." },
      { speaker: "self", text: "As partners, we are building a steady daily life by caring for the small things." },
    ], [{ speaker: "other", text: "I will make dinner when you get home, partner." }, { speaker: "self", text: "That is the everyday care I value in our relationship." }]),
    scenario("stage_accurate", "anniversary-note", "Anniversary Note", "Partners mark an important anniversary with appreciation for their relationship.", "relationship milestone", [
      { speaker: "self", text: "I cannot believe it has been a year since we decided to be together." },
      { speaker: "other", text: "I know. I feel grateful for how much we have learned as partners." },
      { speaker: "self", text: "My favorite part is that we still make room for honest conversations." },
      { speaker: "other", text: "And we still make each other laugh when life gets heavy." },
      { speaker: "self", text: "Celebrating a year together reminds me that we are committed partners." },
    ], [{ speaker: "other", text: "Me too. I am proud of our relationship." }, { speaker: "self", text: "I am proud of us." }]),
    scenario("stage_accurate", "social-circles", "Social Circles", "Partners coordinate introductions into each other's social circles.", "social circle introduction", [
      { speaker: "self", text: "My friends are having dinner Sunday, and I would like you to come with me." },
      { speaker: "other", text: "I would be glad to meet them. Is there anything I should know?" },
      { speaker: "self", text: "They are warm, and I will stay close if you need a break." },
      { speaker: "other", text: "Thank you. I want to know the people important to you." },
      { speaker: "self", text: "I am excited to bring my partner into the social circle that matters to me." },
    ], [{ speaker: "other", text: "I am excited too." }, { speaker: "self", text: "We will go together." }]),
    scenario("constructive", "repair-small-conflict", "Repair Small Conflict", "Partners repair a small conflict with accountability and care.", "relationship repair", [
      { speaker: "self", text: "I was short with you this morning, partner, and that was not fair in our relationship." },
      { speaker: "other", text: "Thank you for saying it. I felt hurt, and I want us as partners to repair it." },
      { speaker: "self", text: "Stress explains it but does not excuse it. I am sorry, and I want to repair the hurt this caused." },
      { speaker: "other", text: "I accept the apology. As your partner, I need you to say when you need a pause next time." },
      { speaker: "self", text: "In our relationship, I want us to repair conflict with accountability and respect." },
    ], [{ speaker: "other", text: "I want that too, partner." }, { speaker: "self", text: "Thank you for repairing this with me as my partner." }]),
    scenario("constructive", "trip-and-near-future", "Trip And Near Future", "Partners plan a trip and a near-term future step together.", "travel and near future", [
      { speaker: "self", text: "As my partner, would you want to plan a short trip together this autumn?" },
      { speaker: "other", text: "Yes. I love planning time away with you as part of our committed relationship." },
      { speaker: "self", text: "Because we are established partners, let us set a shared budget and choose dates before booking." },
      { speaker: "other", text: "That feels good. We can also talk about our winter plans as partners while we are there." },
      { speaker: "self", text: "Planning a trip and our next season together feels right in our committed relationship." },
    ], [{ speaker: "other", text: "Me too, partner." }, { speaker: "self", text: "Let us plan the trip and our near future this weekend." }]),
  ],
  LONG_DISTANCE: [
    scenario("stage_accurate", "time-zone-routine", "Time Zone Routine", "Partners in different time zones protect a small daily connection.", "time zone communication", [
      { speaker: "self", text: "Good morning from my side of the world. I hope your evening is gentle." },
      { speaker: "other", text: "Good evening. Your message arrived right as I finished work." },
      { speaker: "self", text: "I know our hours barely overlap, so I wanted to use this window." },
      { speaker: "other", text: "I appreciate it. These small check ins keep me close to you." },
      { speaker: "self", text: "We are still partners across time zones, so these overlap windows matter to me." },
    ], [{ speaker: "other", text: "I will look for it in the morning." }, { speaker: "self", text: "Sleep well when you get there." }]),
    scenario("stage_accurate", "online-date-night", "Online Date Night", "Long-distance partners plan an intentional online date.", "online date", [
      { speaker: "self", text: "Would you like to make Friday our online date night?" },
      { speaker: "other", text: "Yes. We could cook the same meal and video call." },
      { speaker: "self", text: "I will send the recipe so we can shop before then." },
      { speaker: "other", text: "I like having something intentional instead of only quick calls." },
      { speaker: "self", text: "Our online date keeps our long-distance relationship intentional between visits." },
    ], [{ speaker: "other", text: "Friday is ours then." }, { speaker: "self", text: "I am looking forward to it." }]),
    scenario("stage_accurate", "countdown-to-visit", "Countdown To Visit", "They wait for their next visit and share the anticipation honestly.", "next visit anticipation", [
      { speaker: "self", text: "Only three weeks until we see each other again." },
      { speaker: "other", text: "I have been counting too. I miss being in the same room." },
      { speaker: "self", text: "I do too. I am trying to enjoy the countdown instead of wishing it away." },
      { speaker: "other", text: "That is a good reminder. We have still been showing up for each other." },
      { speaker: "self", text: "Waiting for our next visit is hard, but we are still choosing this long-distance relationship." },
    ], [{ speaker: "other", text: "I cannot wait to hug you." }, { speaker: "self", text: "Me neither." }]),
    scenario("constructive", "cancelled-flight-replan", "Cancelled Flight Replan", "A cancelled flight interrupts a visit, and they replan without blaming each other.", "flight cancellation", [
      { speaker: "self", text: "As your long-distance partner in another city, I am disappointed that my flight was cancelled." },
      { speaker: "other", text: "I am disappointed too, but our relationship has survived the distance, and this is not your fault." },
      { speaker: "self", text: "Thank you. I can take the next available flight on Tuesday and keep our visit plans on track." },
      { speaker: "other", text: "Tuesday works. Even across cities, we can keep showing up for this relationship after travel changes." },
      { speaker: "self", text: "The visit is still ahead of us after the cancelled flight, and we are rescheduling it together." },
    ], [{ speaker: "other", text: "We will make the new visit count." }, { speaker: "self", text: "I am grateful for your patience." }]),
    scenario("constructive", "remote-rhythm-reset", "Remote Rhythm Reset", "They adjust their long-distance communication rhythm to protect both connection and rest.", "remote rhythm adjustment", [
      { speaker: "self", text: "Our late calls are making me tired, even though I love hearing you." },
      { speaker: "other", text: "I noticed it too. I do not want connection to cost you rest." },
      { speaker: "self", text: "Could we do shorter weekday calls and save one longer call for weekends?" },
      { speaker: "other", text: "Yes, and we can leave voice notes when time zones do not match." },
      { speaker: "self", text: "This new rhythm helps our long-distance relationship stay connected without exhausting us." },
    ], [{ speaker: "other", text: "Distance needs flexibility." }, { speaker: "self", text: "We can keep adapting together." }]),
  ],
  ON_A_BREAK: [
    scenario("stage_accurate", "two-week-pause", "Two Week Pause", "Partners agree to a defined relationship pause and name its duration.", "defined break duration", [
      { speaker: "self", text: "I think we need a pause to reflect without trying to solve everything at once." },
      { speaker: "other", text: "I agree. Would two weeks give us enough room to think?" },
      { speaker: "self", text: "Two weeks feels clear and manageable to me." },
      { speaker: "other", text: "Then we are pausing until the fifteenth." },
      { speaker: "self", text: "We are still on a two-week relationship pause until the fifteenth." },
    ], [{ speaker: "other", text: "I will hold that boundary." }, { speaker: "self", text: "Thank you." }]),
    scenario("stage_accurate", "no-contact-boundary", "No Contact Boundary", "During an agreed break, they clarify that they will not contact each other except for emergencies.", "break contact boundary", [
      { speaker: "self", text: "For this pause to work, I need us not to message except for a real emergency." },
      { speaker: "other", text: "I can respect that, even though it will be hard." },
      { speaker: "self", text: "I am not trying to punish you. I need quiet to hear my own thoughts." },
      { speaker: "other", text: "I understand. I will not reach out casually during the break." },
      { speaker: "self", text: "We are still paused, so no casual contact is part of the boundary." },
    ], [{ speaker: "other", text: "We are still on the agreed pause." }, { speaker: "self", text: "Yes, until our check-in." }]),
    scenario("stage_accurate", "check-in-agreement", "Check In Agreement", "They set a limited check-in plan while the relationship pause continues.", "break check-in plan", [
      { speaker: "self", text: "Would one brief check-in halfway through the break feel useful?" },
      { speaker: "other", text: "Yes, as long as it is only to confirm we are okay, not to reopen everything." },
      { speaker: "self", text: "That is what I mean. A simple message on Sunday." },
      { speaker: "other", text: "I can do that and keep the rest of the pause intact." },
      { speaker: "self", text: "This brief check-in does not end the pause; the space still matters." },
    ], [{ speaker: "other", text: "We will keep the check-in brief." }, { speaker: "self", text: "Agreed." }]),
    scenario("constructive", "reflection-progress", "Reflection Progress", "They share limited reflection progress at an agreed check-in, without ending the pause.", "break reflection", [
      { speaker: "self", text: "At our agreed check-in, I want to share what I have learned about my part." },
      { speaker: "other", text: "Thank you. I have been journaling about what I need too." },
      { speaker: "self", text: "I am not ready to decide anything yet, but the pause is helping me see patterns." },
      { speaker: "other", text: "I feel similarly. I want to keep respecting the remaining time." },
      { speaker: "self", text: "We can share what we have learned while the relationship pause remains active." },
    ], [{ speaker: "other", text: "Okay, we will talk on the review date." }, { speaker: "self", text: "Take care until then." }]),
    scenario("constructive", "review-date-set", "Review Date Set", "They set a date to review the relationship while remaining actively on a break.", "break review date", [
      { speaker: "self", text: "Can we set a date to review what we learned during this pause?" },
      { speaker: "other", text: "Yes, the twenty-second gives me enough time to reflect." },
      { speaker: "self", text: "That works for me. Until then, the pause stays in place." },
      { speaker: "other", text: "Agreed. Setting the date does not mean we are resuming yet." },
      { speaker: "self", text: "The review date is not a reunion; we remain on the relationship pause until then." },
    ], [{ speaker: "other", text: "I will see you at the review conversation." }, { speaker: "self", text: "Until then, we keep the pause." }]),
  ],
  BREAKUP_DISCUSSION: [
    scenario("stage_accurate", "incompatibility-talk", "Incompatibility Talk", "Partners discuss possible incompatibilities but have not formally ended the relationship.", "incompatibility discussion", [
      { speaker: "self", text: "I keep noticing that we want very different daily lives." },
      { speaker: "other", text: "I have noticed it too, especially around how much independence we each need." },
      { speaker: "self", text: "It makes me wonder whether caring for each other is enough for long term fit." },
      { speaker: "other", text: "That is painful, but I think it is an honest question." },
      { speaker: "self", text: "We are discussing incompatibility, and no formal end has been decided." },
    ], [{ speaker: "other", text: "Let us keep talking before we decide anything." }, { speaker: "self", text: "Yes, no final decision tonight." }]),
    scenario("stage_accurate", "unmet-needs", "Unmet Needs", "They discuss long-term needs that have repeatedly gone unmet without ending things in this conversation.", "unmet long-term needs", [
      { speaker: "self", text: "I need more emotional availability in our relationship, and I am wondering whether we should end it." },
      { speaker: "other", text: "I hear that. I do not know whether ending the relationship is right, but my work stress has hurt us." },
      { speaker: "self", text: "Before we decide whether to end this relationship, I need to know whether the pattern can truly change." },
      { speaker: "other", text: "I cannot promise quickly, so I think we need more honest conversations before making a final decision." },
      { speaker: "self", text: "My unmet needs are serious, but we are still discussing rather than ending the relationship." },
    ], [{ speaker: "other", text: "We have not made a final choice." }, { speaker: "self", text: "No, we are still talking." }]),
    scenario("stage_accurate", "distance-pressure", "Distance Pressure", "Partners face strain from distance and discuss its impact before any final outcome.", "distance strain", [
      { speaker: "self", text: "The distance is wearing on me more than I expected." },
      { speaker: "other", text: "I feel it too. Plans to close the distance keep moving further away." },
      { speaker: "self", text: "I am scared that the waiting is changing how connected we feel." },
      { speaker: "other", text: "I understand. We need to talk honestly about whether this is sustainable." },
      { speaker: "self", text: "Distance is pressuring us, and we are still deciding whether the relationship can continue." },
    ], [{ speaker: "other", text: "Let us give this conversation the time it needs." }, { speaker: "self", text: "I agree." }]),
    scenario("constructive", "explore-repair", "Explore Repair", "They explore whether repair is possible while explicitly keeping the outcome undecided.", "exploring repair", [
      { speaker: "self", text: "Before we decide whether to end this, I want to ask if repair feels possible to you." },
      { speaker: "other", text: "I do not know yet, but I am willing to look at what would need to change." },
      { speaker: "self", text: "For me, repair would need consistent follow through, not only good intentions." },
      { speaker: "other", text: "That is fair. I need to consider whether I can offer that consistently." },
      { speaker: "self", text: "We are exploring repair without promising that the relationship will continue." },
    ], [{ speaker: "other", text: "That feels honest." }, { speaker: "self", text: "We can continue the discussion soon." }]),
    scenario("constructive", "near-closing-not-ended", "Near Closing Not Ended", "They acknowledge that the relationship may be nearing an end but do not formally close it.", "near ending discussion", [
      { speaker: "self", text: "I feel like we may be close to a painful ending, even if we have not said it." },
      { speaker: "other", text: "I feel that too. I do not want either of us to be surprised by it." },
      { speaker: "self", text: "I want us to be gentle and clear as we keep talking." },
      { speaker: "other", text: "Yes. We owe each other care, whatever we eventually decide." },
      { speaker: "self", text: "We may be near an ending, but we have not formally ended the relationship." },
    ], [{ speaker: "other", text: "I can meet you in that honesty." }, { speaker: "self", text: "Thank you." }]),
  ],
  RECONNECTING: [
    scenario("stage_accurate", "months-later-hello", "Months Later Hello", "After months apart, one person sends a careful first message.", "first contact after months", [
      { speaker: "self", text: "Hi. I know it has been months, and I hope you have been well." },
      { speaker: "other", text: "Hi. I was surprised to hear from you, but I appreciate the gentle message." },
      { speaker: "self", text: "There is no pressure to reply beyond what feels right." },
      { speaker: "other", text: "Thank you. I am open to a brief conversation." },
      { speaker: "self", text: "We are cautiously reconnecting after months apart, not returning to what we had before." },
    ], [{ speaker: "other", text: "We can start with a little catching up." }, { speaker: "self", text: "That sounds good." }]),
    scenario("stage_accurate", "apology-after-pause", "Apology After Pause", "One person offers a specific apology after time apart, without assuming reconciliation.", "post-pause apology", [
      { speaker: "self", text: "I have reflected on how I handled our last conversation, and I am sorry for shutting down." },
      { speaker: "other", text: "I appreciate the specific apology. That silence was hard for me." },
      { speaker: "self", text: "You deserved a clearer response. I am not asking you to erase the impact." },
      { speaker: "other", text: "Thank you. I need time, but it matters that you understand it." },
      { speaker: "self", text: "This apology begins careful contact after the pause; it is not a restart of the relationship." },
    ], [{ speaker: "other", text: "We can see what future contact feels okay." }, { speaker: "self", text: "I will follow your pace." }]),
    scenario("stage_accurate", "life-update-after-time", "Life Update After Time", "They exchange low-stakes updates after separating, without returning to prior closeness.", "separation life update", [
      { speaker: "self", text: "Since our relationship ended and we stopped contact, I heard you moved apartments and hoped you were well." },
      { speaker: "other", text: "It is kind of you to ask after our time apart. I have been settling in slowly and focusing on work." },
      { speaker: "self", text: "I am glad. After months apart, I have been taking classes and do not expect us to return to old closeness." },
      { speaker: "other", text: "That feels right. We can exchange a simple update without treating it as getting back together." },
      { speaker: "self", text: "We can exchange simple updates after separation without assuming renewed closeness." },
    ], [{ speaker: "other", text: "This careful pace feels comfortable after our time apart." }, { speaker: "self", text: "I am glad we are only reconnecting at a pace that feels safe." }]),
    scenario("constructive", "careful-coffee", "Careful Coffee", "They cautiously consider meeting for coffee, with clear permission to decline.", "cautious coffee", [
      { speaker: "self", text: "Since we ended the relationship, would you be open to a short coffee only if it feels comfortable?" },
      { speaker: "other", text: "I might be open to a short coffee after our time apart, but it would not mean we are back together." },
      { speaker: "self", text: "Thank you. You can change your mind, and meeting for coffee would not restart the relationship." },
      { speaker: "other", text: "I appreciate that. A weekday afternoon would feel safest for a cautious reconnection." },
      { speaker: "self", text: "A short coffee would only be a cautious reconnection, not a return to the relationship." },
    ], [{ speaker: "other", text: "Let me check my week before deciding whether to meet." }, { speaker: "self", text: "Take your time; there is no expectation to resume anything." }]),
    scenario("constructive", "slow-rebuild-boundaries", "Slow Rebuild Boundaries", "They set clear boundaries for a slow, careful reconnection.", "slow reconnection boundaries", [
      { speaker: "self", text: "If we reconnect, I need us to move slowly and speak up early when something feels hard." },
      { speaker: "other", text: "I can agree to that. I also need regular space to reflect alone." },
      { speaker: "self", text: "That sounds healthy. We do not need to recreate what we had before." },
      { speaker: "other", text: "Exactly. We are seeing whether a new kind of connection is possible." },
      { speaker: "self", text: "We are rebuilding contact slowly with boundaries, not resuming the old relationship." },
    ], [{ speaker: "other", text: "We can check in after a few weeks." }, { speaker: "self", text: "That feels right." }]),
  ],
  ENDED: [
    scenario("stage_accurate", "mutual-goodbye", "Mutual Goodbye", "They clearly and mutually say goodbye to the relationship.", "mutual ending", [
      { speaker: "self", text: "After all our conversations, I believe ending this relationship is the right choice." },
      { speaker: "other", text: "I agree. It hurts, but I know we have reached the end." },
      { speaker: "self", text: "I want to say goodbye with respect for what we shared." },
      { speaker: "other", text: "I want that too. I do not regret caring about you." },
      { speaker: "self", text: "Our relationship has ended, and this goodbye is final." },
    ], [{ speaker: "other", text: "Goodbye, and I wish you well." }, { speaker: "self", text: "Goodbye." }]),
    scenario("stage_accurate", "return-belongings", "Return Belongings", "After ending the relationship, they arrange to return belongings with minimal contact.", "returning belongings", [
      { speaker: "self", text: "Since our relationship ended, I found your jacket and the book you lent me." },
      { speaker: "other", text: "Thank you. Could you leave them with the building desk so we do not need to meet after the breakup?" },
      { speaker: "self", text: "Yes, I will label the bag and send one final confirmation after I drop it off." },
      { speaker: "other", text: "That works. After the belongings are returned, there will be no more logistics between us." },
      { speaker: "self", text: "I will respect the distance because our relationship has ended." },
    ], [{ speaker: "other", text: "Thank you for returning them after the end of our relationship." }, { speaker: "self", text: "You are welcome. There is nothing further between us." }]),
    scenario("stage_accurate", "no-further-contact", "No Further Contact", "They explicitly confirm that there will be no further contact after the relationship ended.", "no contact after ending", [
      { speaker: "self", text: "For my healing, I need us not to contact each other after today." },
      { speaker: "other", text: "I understand and will respect that boundary." },
      { speaker: "self", text: "This is not meant to punish you. I need a clean end." },
      { speaker: "other", text: "I hear you. I will not reach out again." },
      { speaker: "self", text: "Our relationship is over, and I need this no-contact boundary to remain final." },
    ], [{ speaker: "other", text: "I wish you peace going forward." }, { speaker: "self", text: "I wish you the same." }]),
    scenario("constructive", "gratitude-and-close", "Gratitude And Close", "They express gratitude and close the relationship without reopening it.", "grateful closure", [
      { speaker: "self", text: "I want to thank you for the good parts of our relationship before we close this." },
      { speaker: "other", text: "Thank you. I am grateful for the care we gave each other too." },
      { speaker: "self", text: "I can hold that gratitude and still know we are finished." },
      { speaker: "other", text: "I feel the same. This is closure, not a new beginning." },
      { speaker: "self", text: "I am grateful for the relationship, and I accept that it is fully over." },
    ], [{ speaker: "other", text: "Take good care of yourself." }, { speaker: "self", text: "You too. Goodbye." }]),
    scenario("constructive", "final-logistics", "Final Logistics", "They complete one last logistical exchange and accept that the relationship has ended.", "final logistics", [
      { speaker: "self", text: "Now that our relationship is over, the shared account is closed and your final receipt is in the envelope." },
      { speaker: "other", text: "Thank you for handling that. I received it, and I understand these are only the final practical details." },
      { speaker: "self", text: "This was the last practical item because we have ended the relationship and will not reopen contact." },
      { speaker: "other", text: "It is the last item on mine too. There is no reason for either of us to contact the other again." },
      { speaker: "self", text: "This is our final logistical message because the relationship is over for good." },
    ], [{ speaker: "other", text: "Understood. I accept that the relationship is over." }, { speaker: "self", text: "Goodbye. There will be no further contact." }]),
  ],
};

module.exports = { STAGE_SCENARIOS };
